version: '2'
services:
  influxdb:
    image: bitnami/influxdb:latest
    container_name: influxdb
    ports:
      - 8086:8086
      - 8085:8088
    environment:
      - INFLUXDB_ADMIN_USER_PASSWORD=bitnami1
      - INFLUXDB_ADMIN_USER_TOKEN=admintoken1
      - INFLUXDB_USER=admin
      - INFLUXDB_USER_PASSWORD=bitnami1
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_DB=my_database
    volumes:
      - influxdb_data:/bitnami/influxdb
volumes:
  influxdb_data:

